### ISSUE TITLE
Defining how far to look ahead

### ISSUE THREAD

**Issue by StillClueless** [vas3k/home-assistant-berlin-transport#19] opened 2023-09-09 11:21 UTC
First of all, awesome integration, many thanks. Also, we seem to live in the same neighbourhood. :-D.

So, it says in the documentation:
After fetching the API, it creates one entity for each stop and writes 10 upcoming departures into attributes.departures.

The behaviour is a bit different for me. It seems to show all connections in the upcoming 5 - 10 minutes. Is there a way to define this time span? For instance set it to 20 or thirty minutes?

**Comment by vas3k** [comment] 2023-09-12 07:05
Hey, neighbor!

Now there is a parameter `walking_time`, which hides all departures with less than N minutes left. Maybe this could help?

```
sensor:
  - platform: berlin_transport
    departures:
      - name: "S+U Schönhauser Allee"
        stop_id: 900110001
        walking_time: 20 # minutes
```

**Comment by cfeld27** [comment] 2023-09-26 08:54
Hi @vas3k, 
Thank you very much for the HA integration. much appreciated.
@StillClueless I see the same issue as you reported, it does not show the next N upcoming departures, instead max. 2 departures per line, sometimes no departures at all. But I am pretty sure that this is no issue caused by the integration, it seems there is an issue with the BVG Transport API. I checked it manually and the API returned exactly the same data as shown in the HA sensor. 
You can try it for your stop / time: 
https://v6.bvg.transport.rest/stops/900196509/departures?when=10:35:53&results=5
I tried to modify the number of results, but even if this is set to 10, it will return max. 2 departures, sometimes no departure. 

You can also try this web app: https://weilsiedichlieben.de/
And you will see that you have the same departures there as the HA integration shows. 

So I think nothing which can be fixed in the HA integration code. Maybe something is wrong with the BVG API. 
Cheers

**Comment by HerrLevin** [comment] 2023-09-28 12:01
@cfeld27 @StillClueless  The VBB/DB-Rest API limits its lookahead to 10 minutes. You can extend this default behavior with the `duration` query parameter. At least in version 5 of the API docs. (https://github.com/derhuerst/vbb-rest/blob/5/docs/api.md#get-stopsiddepartures)

You could add this functionality by adding a `"duration": 30` in https://github.com/vas3k/home-assistant-berlin-transport/blob/2be9e756490a2817e19bcbc0b18bf6518f2ab635/custom_components/berlin_transport/sensor.py#L128-L132

**Comment by cfeld27** [comment] 2023-10-04 09:27
@HerrLevin that worked perfectly fine. Thanks a lot!

**Closed** 2023-12-29 10:07 UTC
